services:
  agent:
    build:
      context: ../cagent/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data/config:/config
      - ./data/work:/work
      - ./skills:/root/.claude/skills:ro
    ports:
      - 9756:8080
    entrypoint:
      [
        "cagent",
        "serve",
        "api",
        "/config/agent.yml",
        "--listen",
        ":8080",
        "--session-db",
        "/config/session.db",
        "--debug",
        "--log-file",
        "/config/debug.agent.log",
      ]

  search-mcp:
    image: ghcr.io/aas-ee/open-web-search:v1.2.0
    environment:
      MODE: http
    expose:
      - 3000
