provider:
  dashscope:
    type: openai-compatible
    baseUrl: https://dashscope.aliyuncs.com/compatible-mode/v1

agents:
  root:
    model: dashscope/qwen3.5-35b-a3b
    instruction: You are a helpful assistant!
    context:
      maxIterations: 100
      addDate: true
    toolset:
      - type: mcp
        name: web-search
      - type: memory
      - type: skill
      - type: shell

mcps:
  web-search:
    remoteType: http
    remoteUrl: http://search-mcp:3000/sse
