provider:
  dashscope:
    type: openai-compatible
    baseUrl: https://dashscope.aliyuncs.com/compatible-mode/v1

  ollama:
    type: openai-compatible
    baseUrl: http://host.docker.internal:11434/v1

agents:
  root:
    model: ollama/qwen3.5:2b
    # model: dashscope/qwen3.5-35b-a3b
    instruction: You are a helpful assistant!
    context:
      maxIterations: 100
    toolset:
      - type: mcp
        name: web-search
      - type: memory
      - type: skill
      - type: shell
        rtkRewrite: auto
      - type: env
      - type: cron
      - type: todo
      - type: filesystem

mcps:
  web-search:
    remoteType: sse
    remoteUrl: http://search-mcp:3000/sse
    filterTools:
      - search
      - fetchWebContent
