services:
  agent:
    image: my-agent:latest
    env_file:
      - .compose-dev.env
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./examples/default.yaml:/app/agent.yaml:ro
      - ./data:/data
    ports:
      - 10080:8080

  # search-mcp:
  #   image: ghcr.io/aas-ee/open-web-search:v1.2.5
  #   environment:
  #     MODE: http
  #   expose:
  #     - 3000
