services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .compose-dev.env
    volumes:
      - ./examples/default.yaml:/app/agent.yaml:ro
      - ./data:/data
    ports:
      - 9756:8080

  search-mcp:
    image: ghcr.io/aas-ee/open-web-search:v1.2.0
    environment:
      MODE: http
    expose:
      - 3000
